const clamp = value => Math.max(0, Math.min(1, value));
export function enableScrollEffects() {
  const reduced = matchMedia("(prefers-reduced-motion: reduce)"); const scene = document.querySelector("[data-home-scene]"); const sheet = document.querySelector("[data-cv-sheet]"); const cv = document.querySelector("#cv"); const work = document.querySelector("#work"); const cards = [...document.querySelectorAll(".project-card")]; const header = document.querySelector("[data-site-header]"); let scheduled = false;
  function render() { scheduled = false; if (reduced.matches) { document.documentElement.style.setProperty("--home-scale", 1); document.documentElement.style.setProperty("--home-opacity", 1); header?.style.setProperty("--header-backdrop", 0); return; }
    const homeDistance = Math.max(1, scene.offsetHeight - innerHeight); const homeProgress = clamp(-scene.getBoundingClientRect().top / homeDistance); const homeScale = 1 + homeProgress * 2; document.documentElement.style.setProperty("--home-scale", homeScale.toFixed(3)); document.documentElement.style.setProperty("--home-opacity", clamp(3 - homeScale).toFixed(3));
    const cvRect = cv.getBoundingClientRect(); const enter = clamp((innerHeight - cvRect.top) / (innerHeight - Math.min(180, innerHeight * .25))); const exit = clamp((innerHeight * .78 - cvRect.bottom) / (innerHeight * .55)); const travel = Math.min(260, innerWidth * .3); const upperX = -travel * (1 - Math.min(1, enter / .75)); const lowerX = -travel * (1 - Math.max(0, (enter - .25) / .75)); sheet.style.setProperty("--cv-opacity", (enter * (1 - exit)).toFixed(3)); sheet.style.setProperty("--cv-x", `${upperX - exit * travel}px`); sheet.style.setProperty("--cv-shear", ((lowerX - upperX) / Math.max(1, sheet.offsetHeight)).toFixed(5)); header?.style.setProperty("--header-backdrop", clamp(Math.max(0, -cvRect.top) / Math.min(360, innerHeight * .45)).toFixed(3));
    const workRect = work.getBoundingClientRect(); const baseEnter = clamp((innerHeight - workRect.top) / innerHeight); const workExit = clamp((innerHeight * .72 - workRect.bottom) / (innerHeight * .85)); const durations = [.78,.58,.38]; cards.forEach((card,index) => { const progress = clamp((baseEnter - (index < 3 ? 0 : .22)) / durations[index % 3]); const opacity = progress * (1 - workExit); card.style.setProperty("--card-opacity", opacity.toFixed(3)); card.style.setProperty("--card-x", `${-180 * (1 - progress) - 150 * workExit}px`); card.style.pointerEvents = opacity > .85 ? "auto" : "none"; });
  }
  function schedule() { if (!scheduled) { scheduled = true; requestAnimationFrame(render); } }
  addEventListener("scroll", schedule, { passive: true }); addEventListener("resize", schedule); addEventListener("pageshow", schedule); reduced.addEventListener("change", schedule); render();
}

export function enableCardTilt() { const allowed = matchMedia("(prefers-reduced-motion: no-preference) and (hover: hover) and (pointer: fine)"); document.querySelectorAll(".project-card").forEach(card => { card.addEventListener("pointermove", event => { if (!allowed.matches) return; const rect = card.getBoundingClientRect(); const x = ((event.clientX - rect.left) / rect.width - .5) * 18; const y = ((event.clientY - rect.top) / rect.height - .5) * -18; card.style.setProperty("--card-tilt", `perspective(720px) rotateX(${y}deg) rotateY(${x}deg) translateY(-16px) scale(1.025)`); }); card.addEventListener("pointerleave", () => card.style.setProperty("--card-tilt", "none")); }); }
